import requests
from utils.generate_env  import generate_env

def protect_decode():
    url = f"{generate_env()['api_module']}/decode"
    body={
        'encoded':"QUFBQWV3QUFBQ0lBQUFCcEFBQUFaQUFBQUY4QUFBQnJBQUFBWlFBQUFIa0FBQUFpQUFBQU9nQUFBQ0FBQUFBaUFBQUFWZ0FBQUU4QUFBQlRBQUFBVXdBQUFFOEFBQUF0QUFBQU13QUFBREFBQUFBeEFBQUFNQUFBQUMwQUFBQkJBQUFBVEFBQUFFb0FBQUJRQUFBQVFnQUFBQzBBQUFBNEFBQUFNZ0FBQURRQUFBQTJBQUFBT0FBQUFFZ0FBQUJYQUFBQUxRQUFBRUlBQUFCV0FBQUFXZ0FBQUVRQUFBQk5BQUFBVXdBQUFFUUFBQUJLQUFBQU5nQUFBRThBQUFBdEFBQUFVd0FBQURrQUFBQkRBQUFBUVFBQUFFZ0FBQUFpQUFBQUxBQUFBQ0FBQUFBaUFBQUFkUUFBQUhNQUFBQmxBQUFBY2dBQUFHNEFBQUJoQUFBQWJRQUFBR1VBQUFBaUFBQUFPZ0FBQUNBQUFBQWlBQUFBZFFBQUFITUFBQUJsQUFBQWNnQUFBRzRBQUFCaEFBQUFiUUFBQUdVQUFBQWlBQUFBZlE9PQ=="
    }
    response = requests.post(url, json=body)
    data = response.json()
    
    isProtec=""
    if data['message'] == 'Success':
        isProtec = True
    elif data['message'] == 'Error':
        isProtec = False
    return isProtec

